name: Build
on:
  # pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-testing-latest
    steps:
    # TODO(setup-ros-docker#7): calling chown is necessary for now
    - run: sudo chown -R rosbuild:rosbuild "$HOME" .
    - run: mkdir src && mv android_node src/android_node && mv android_node_interfaces src/android_node_interfaces
    - run: ls /opt/ros && colcon build
    
