name: Build
on:
  # pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-testing-latest
    steps:
    # TODO(setup-ros-docker#7): calling chown is necessary for now
    - run: sudo chown -R rosbuild:rosbuild "$HOME" .
    - uses: ros-tooling/action-ros-ci@0.0.16
      with:
        package-name: |
          android_node
          android_node_interfaces
          
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
